# Generated by Django 3.2.3 on 2021-05-21 03:53

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reservation"),
    ]

    operations = [BtreeGistExtension()]
