# Generated by Django 3.2.3 on 2021-05-21 23:37

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_auto_20210521_0353"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=(
                    (
                        reservation.models.TsTzRange(
                            "from_date",
                            "to_data",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("room", "="),
                ),
                name="exclude_overlapping_reservations",
            ),
        ),
    ]
