# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    env: # Or as an environment variable
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      ENGINE: ${{ secrets.ENGINE }}
      NAME: ${{ secrets.NAME }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.6

      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/poetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: | 
            ${{runner.os}}-poetry-
          
      - name: Install Dependencies
        run: poetry install

      - name: Run migrations
        working-directory: meetingroomanager
        run: poetry run python manage.py migrate
      
      - name: Run tests
        working-directory: meetingroomanager
        run: poetry run python manage.py test
